require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'
target 'TipotieNavi' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  source 'https://github.com/CocoaPods/Specs.git'
  source 'https://bitbucket.org/nimbledevices/steerpath-mapbox-ios-podspec.git'
  source 'https://bitbucket.org/nimbledevices/steerpath-smart-sdk-podspec.git'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  target 'TipotieNaviTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end

target 'TipotieNavi-tvOS' do
  # Pods for TipotieNavi-tvOS

  target 'TipotieNavi-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end